'TODO: INSTANT VB TODO TASK: There is no equivalent to #pragma directives in VB.NET:
'#pragma warning disable 1591
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System.Data.Linq
	Imports System.Data.Linq.Mapping
	Imports System.Data
	Imports System.Collections.Generic
	Imports System.Reflection
	Imports System.Linq
	Imports System.Linq.Expressions
	Imports System.ComponentModel
	Imports System
Namespace DXWebApplication23.Models


	<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Documents")> _
	Partial Public Class DataClassesDataContext
		Inherits System.Data.Linq.DataContext

		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()

	#Region "Extensibility Method Definitions"
	Partial Private Sub OnCreated()
	End Sub
	Partial Private Sub InsertDoc(ByVal instance As Doc)
	End Sub
	Partial Private Sub UpdateDoc(ByVal instance As Doc)
	End Sub
	Partial Private Sub DeleteDoc(ByVal instance As Doc)
	End Sub
	#End Region

		Public Sub New()
			MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("DocumentsConnectionString").ConnectionString, mappingSource)
			OnCreated()
		End Sub

		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated()
		End Sub

		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated()
		End Sub

		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated()
		End Sub

		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated()
		End Sub

		Public ReadOnly Property Docs() As System.Data.Linq.Table(Of Doc)
			Get
				Return Me.GetTable(Of Doc)()
			End Get
		End Property
	End Class

	<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Docs")> _
	Partial Public Class Doc
		Implements INotifyPropertyChanging, INotifyPropertyChanged

		Private Shared emptyChangingEventArgs As New PropertyChangingEventArgs(String.Empty)

		Private _Id As Integer

		Private _DocBytes As System.Data.Linq.Binary

		Private _Comment As String

	#Region "Extensibility Method Definitions"
	Partial Private Sub OnLoaded()
	End Sub
	Partial Private Sub OnValidate(ByVal action As System.Data.Linq.ChangeAction)
	End Sub
	Partial Private Sub OnCreated()
	End Sub
	Partial Private Sub OnIdChanging(ByVal value As Integer)
	End Sub
	Partial Private Sub OnIdChanged()
	End Sub
	Partial Private Sub OnDocBytesChanging(ByVal value As System.Data.Linq.Binary)
	End Sub
	Partial Private Sub OnDocBytesChanged()
	End Sub
	Partial Private Sub OnCommentChanging(ByVal value As String)
	End Sub
	Partial Private Sub OnCommentChanged()
	End Sub
	#End Region

		Public Sub New()
			OnCreated()
		End Sub

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=True, IsDbGenerated:=True)> _
		Public Property Id() As Integer
			Get
				Return Me._Id
			End Get
			Set(ByVal value As Integer)
				If (Me._Id <> value) Then
					Me.OnIdChanging(value)
					Me.SendPropertyChanging()
					Me._Id = value
					Me.SendPropertyChanged("Id")
					Me.OnIdChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DocBytes", DbType:="VarBinary(MAX)", UpdateCheck:=UpdateCheck.Never)> _
		Public Property DocBytes() As System.Data.Linq.Binary
			Get
				Return Me._DocBytes
			End Get
			Set(ByVal value As System.Data.Linq.Binary)
				If (Me._DocBytes IsNot value) Then
					Me.OnDocBytesChanging(value)
					Me.SendPropertyChanging()
					Me._DocBytes = value
					Me.SendPropertyChanged("DocBytes")
					Me.OnDocBytesChanged()
				End If
			End Set
		End Property

		<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Comment", DbType:="NVarChar(MAX)")> _
		Public Property Comment() As String
			Get
				Return Me._Comment
			End Get
			Set(ByVal value As String)
				If (Me._Comment <> value) Then
					Me.OnCommentChanging(value)
					Me.SendPropertyChanging()
					Me._Comment = value
					Me.SendPropertyChanged("Comment")
					Me.OnCommentChanged()
				End If
			End Set
		End Property

		Public Event PropertyChanging As PropertyChangingEventHandler Implements INotifyPropertyChanging.PropertyChanging

		Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged

		Protected Overridable Sub SendPropertyChanging()
			If (Me.PropertyChangingEvent IsNot Nothing) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub

		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As String)
			If (Me.PropertyChangedEvent IsNot Nothing) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
End Namespace
'TODO: INSTANT VB TODO TASK: There is no equivalent to #pragma directives in VB.NET:
'#pragma warning restore 1591
