Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace DXWebApplication23.Models

	Partial Public Class Doc
		Public Property Id() As Integer
		Public Property DocBytes() As Byte()
		Public Property Comments() As String
	End Class
End Namespace
