Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace DXWebApplication23.Models

	Partial Public Class DocumentsEntities
		Inherits DbContext

		Public Sub New()
			MyBase.New("name=DocumentsEntities")
		End Sub

		Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
			Throw New UnintentionalCodeFirstException()
		End Sub

		Public Overridable Property Docs() As DbSet(Of Doc)
	End Class
End Namespace
